### ISSUE TITLE
Max function with Group by clause resulting in wrong outputs

### ISSUE THREAD

**Issue by nvamsimohan** [dumbmatter/csv-sql-live#3]
Hi, when I tried to run SELECT "Race" , max("Capital Loss") FROM "TCI" group by "Race"
I get these results- 

Amer_Indian_Eskimo - 1980
Asian_Pac_Islander - 2457
Black - 625
Other - 625
White - 974

Although the results for first two entries are correct, Max values pulled for bottom three are wrong (they should have been 4356, 2179 and 4356 respectively).
You can check the data here - https://raw.githubusercontent.com/nvamsimohan/DallasDSA/main/Tarrant%20County%20Income%20Dataset.csv
[Tarrant County Income Dataset (1).csv](https://github.com/dumbmatter/csv-sql-live/files/10959641/Tarrant.County.Income.Dataset.1.csv)

Excel/Tableau/MS SSMS all gives correct values except for above. Any assistance is greatly appreciated.

Thanks much,
![sql error](https://user-images.githubusercontent.com/4365176/224770761-d06c2324-78b1-43cb-9288-0ae2fed525df.png)

Vam.

**Comment by dumbmatter** [comment]
It's a pretty naive tool, it imports all the columns as strings, so in your example it's sorting them as strings too. To do numeric rather than alphabetic comparison you'd need something like:

```SELECT "Race" , max(CAST("Capital Loss" AS NUMBER)) FROM "TCI" group by "Race"```

**Comment by nvamsimohan** [comment]
Thank you so much Jeremy, Appreciate all your hard work.
